### ISSUE TITLE
Replace Travis CI with GitHub Actions

### ISSUE THREAD

**Issue by fank** [enthus-golang/gowsdl#8]
## Description
The project currently references Travis CI in the README, but Travis CI has become less accessible for open source projects. We should migrate to GitHub Actions for CI/CD.

### 1. Create GitHub Actions workflow
Create `.github/workflows/ci.yml`:
```yaml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.txt ./...
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
    
    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
```

### 2. Add release workflow
Create `.github/workflows/release.yml` for automated releases

### 3. Update README
- Remove Travis CI badge
- Add GitHub Actions badge
- Update build status link

## Benefits
- Free for public repositories
- Better integration with GitHub
- More powerful and flexible
- Active development and support
